services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    # command: start --proxy-headers xforwarded --hostname=sso.singha.local --http-enabled=true --hostname-strict=false
    command: start --proxy-headers xforwarded --http-enabled=true --hostname-strict=false
    environment:
      KC_HOSTNAME: "https://sso.singha.local"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: inmad
      KC_DB: mssql
      KC_DB_URL: "jdbc:sqlserver://${DB_HOST};databaseName=SSO;user=sa;password=**h3ll0123;trustServerCertificate=true;encrypt=false;"
    ports:
      - "8080:8080"