networks:
  singha:
    driver: bridge
volumes:
  redis-data:
  # mongodb-data:
services:
  sso:
    image: quay.io/keycloak/keycloak:26.2
    command: start
    # env_file:
    #   - path: .env
    environment:
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME: "https://sso.singha.local"
      KC_HOSTNAME_STRICT: "false"
      KC_DB: mssql
      KC_DB_URL: "jdbc:sqlserver://${DB_HOST};databaseName=${KC_DB_NAME};user=${KC_DB_USERNAME};password=${KC_DB_PASSWORD};trustServerCertificate=true;encrypt=false;"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - singha
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - singha
  s3:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - /mnt/d/data:/data
    environment:
      MINIO_BROWSER_REDIRECT_URL: "https://s3.singha.local/console"
      MINIO_CONSOLE_SUBPATH: "/console"
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server --console-address ":9001" /data
    restart: unless-stopped
    networks:
      - singha
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb-data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   restart: unless-stopped
  #   networks:
  #     - singha


# ~/.bash_alaises
# alias dock='docker compose'
# alias redock='docker compose up --force-recreate --no-deps'