version: '2.3'
services:
  web: &WEB
    # build:
    #   context: .
    image: nagaworld/canvas-lms
    links:
      - redis
    volumes:
      - ./config/database.yml:/var/canvas/config/database.yml
      - ./config/domain.yml:/var/canvas/config/domain.yml
      - api_docs:/var/canvas/public/doc/api
      - brandable_css_brands:/var/canvas/app/stylesheets/brandable_css_brands
      # - bundler:/home/docker/.bundle/
      # - canvas-docker-gems:/home/docker/.gem/
      - canvas-planner_node_modules:/var/canvas/packages/canvas-planner/node_modules
      - jest-moxios-utils_node_modules:/var/canvas/packages/jest-moxios-utils/node_modules
      - js-utils_es:/var/canvas/packages/js-utils/es
      - js-utils_lib:/var/canvas/packages/js-utils/lib
      - js-utils_node_modules:/var/canvas/packages/js-utils/node_modules
      - k5uploader_es:/var/canvas/packages/k5uploader/es
      - k5uploader_lib:/var/canvas/packages/k5uploader/lib
      - k5uploader_node_modules:/var/canvas/packages/k5uploader/node_modules
      - locales:/var/canvas/config/locales/generated
      - log:/var/canvas/log
      - node_modules:/var/canvas/node_modules
      - old-copy-of-react-14-that-is-just-here-so-if-analytics-is-checked-out-it-doesnt-change-yarn.lock_node_modules:/var/canvas/packages/old-copy-of-react-14-that-is-just-here-so-if-analytics-is-checked-out-it-doesnt-change-yarn.lock/node_modules
      - pacts:/var/canvas/pacts
      - public_dist:/var/canvas/public/dist
      - reports:/var/canvas/reports
      - styleguide:/var/canvas/app/views/info
      - tmp:/var/canvas/tmp
      - translations:/var/canvas/public/javascripts/translations
      - yardoc:/var/canvas/.yardoc
      # - yarn-cache:/home/docker/.cache/yarn
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: palaogman
    networks:
      - singha
    command:
      - /bin/bash
      - -c
      - |
        bundle config set --local path vendor/bundle
        bundle install
        bundle exec rake canvas:compile_assets
      # bundle exec rake db:initial_setup
      # bundle exec rake db:migrate
    

  # jobs:
  #   <<: *WEB
  #   command:  bundle install && bundle exec rake db:initial_setup && bundle exec rake db:migrate
  #   networks:
  #     - singha

  redis:
    image: redis:alpine
    networks:
      - singha

networks:
  singha:
    name: "local"
    external: true
volumes:
  api_docs: {}
  brandable_css_brands: {}
  bundler: {}
  canvas-docker-gems: {}
  canvas-planner_node_modules: {}
  i18nliner_node_modules: {}
  jest-moxios-utils_node_modules: {}
  js-utils_es: {}
  js-utils_lib: {}
  js-utils_node_modules: {}
  k5uploader_es: {}
  k5uploader_lib: {}
  k5uploader_node_modules: {}
  locales: {}
  log: {}
  node_modules: {}
  old-copy-of-react-14-that-is-just-here-so-if-analytics-is-checked-out-it-doesnt-change-yarn.lock_node_modules: {}
  pg_data: {}
  pacts: {}
  public_dist: {}
  reports: {}
  styleguide: {}
  tmp: {}
  translations: {}
  yardoc: {}
  yarn-cache: {}
