services:
  vault:
    restart: unless-stopped
    image: infisical/infisical:latest-postgres
    env_file: .env
    ports:
      - 8081:8080
    environment:
      - NODE_ENV=production
    networks:
      - singha
networks:
  singha:
    external: true
    name: singha
    
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
